config/routes.rb
Rails.application.routes.draw do

  # authentication routes
  devise_for :users, sign_out_via: [:get, :post]

  # Defines the root path route ("/")
  root "articles#index"

  # resources articles
  resources :articles do
    resources :comments
  end

  # resources followers
  resources :followers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, :user_id, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Visible

  belongs_to :article
  belongs_to :user

  validates :article_id, :commenter, :body, :user_id, presence: true
end

app/models/concerns/visible.rb
# frozen_string_literal: true

# this module allows to determine the visibility of an article or comment.
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public private archived].freeze

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/follower.rb
# frozen_string_literal: true

class Follower < ApplicationRecord
  belongs_to :followed_by, class_name: 'User', foreign_key: 'followed_by_user_id'
  belongs_to :followed_user, class_name: 'User', foreign_key: 'followed_user_id'

  validates :followed_by_user_id, :followed_user_id, presence: true

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :article, dependent: :destroy
  has_one :comment, dependent: :destroy
  has_many :followers, class_name: 'Follower', foreign_key: 'followed_user_id', dependent: :destroy
  has_many :following, class_name: 'Follower', foreign_key: 'followed_by_user_id', dependent: :destroy

  validates :name, presence: true

  # get user full name
  def full_name
    "#{name} #{last_name}"
  end

  # get followed association if user is followed by another user
  def followed_by(followed_by_user_id)
    followers.where(followed_by_user_id: followed_by_user_id).first
  end

  # user is followed by another user ?
  def followed_by?(followed_by_user_id)
    followers.where(followed_by_user_id: followed_by_user_id).present?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name last_name])
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# Article controller
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :verify_owner, only: %i[edit destroy]

  def index
    # list of articles
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @user = @article.user
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path, status: :see_other
  end

  private

  # verify if the user in session is the owner of the article
  def verify_owner
    @article = Article.find(params[:id])
    redirect_to action: 'index' unless user_signed_in? && @article.user_id == current_user.id
  rescue StandardError
    redirect_to action: 'index'
  end

  def article_params
    params.require(:article).permit(:title, :body, :status, :user_id)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# articles comments controller
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    if user_signed_in? && @comment.user_id == current_user.id
      @comment.destroy
      redirect_to article_path(@article), status: 303
    else
      redirect_to article_path(@article), status: :unauthorized
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status, :user_id)
  end
end

app/controllers/followers_controller.rb
# frozen_string_literal: true

class FollowersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all.where.not(id: current_user.id)
  end

  def create
    Follower.new(follower_params).save
    redirect_back_or_to root_path
  end

  def destroy
    follower = Follower.find(params[:id])
    follower.destroy

    redirect_back_or_to root_path
  rescue StandardError
    redirect_back_or_to root_path
  end

  private

  def follower_params
    params.require(:follower).permit(:followed_user_id, :followed_by_user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/visible_helper.rb
# frozen_string_literal: true

module VisibleHelper
  # visible status [[Text,Value],[]]
  VALID_STATUSES = [%w[Public public], %w[Private private], %w[Archived archived]].freeze

  # get valid statuses for visibility
  def valid_statuses
    VALID_STATUSES
  end
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class="card">
    <div class="card-body">
      <%= form.hidden_field :user_id, value: current_user.id %>
      <div class="mb-3">
        <%= form.label :title, class: 'form-label' %>
        <%= form.text_field :title, class: 'form-control', placeholder: 'Article title', required: 'require' %>
        <% article.errors.full_messages_for(:title).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>

      <div class="mb-3">
        <%= form.label :body, class: 'form-label' %>
        <%= form.text_area :body, class: 'form-control', rows: 3, required: 'require', minlength: 10 %>
        <% article.errors.full_messages_for(:body).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>

      <div class="mb-3">
        <%= form.label :status, class: 'form-label' %>
        <%= form.select :status, valid_statuses, {}, { class: 'form-control' } %>
      </div>

      <div>
        <%= form.submit class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% content_for :blog_body do %>
  <%= render 'layouts/blog/breadcrumb', data: { :current => 'Edit article', :breadcrumb => [{ :name => 'Home', :url => root_path }] } %>

  <h1 align="center">Edit Article</h1>

  <%= render "form", article: @article %>
<% end %>

app/views/articles/index.html.erb
<% content_for :blog_body do %>
  <%= render 'layouts/blog/breadcrumb', data: { :current => 'Home', :breadcrumb => [] } %>

  <h1 align="center">Articles</h1>

  <div class="list-group">
    <% @articles.each do |article| %>
      <% unless article.archived? %>
        <%= link_to article, class: 'list-group-item list-group-item-action' do %>
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= article.title %></h5>
            <small><%= time_ago_in_words(article.created_at) %></small>
          </div>
          <p class="mb-1 text-truncate"><%= article.body %></p>
          <small><%= article.comments.size %> comments</small>
        <% end %>
      <% end %>
      </div>

    <% end %>
<% end %>

app/views/articles/new.html.erb
<% content_for :blog_body do %>
  <%= render 'layouts/blog/breadcrumb', data: { :current => 'New article', :breadcrumb => [{ :name => 'Home', :url => root_path }] } %>

  <h1 align="center">New Article</h1>

  <%= render "form", article: @article %>

<% end %>

app/views/articles/show.html.erb
<% content_for :blog_body do %>
  <%= render 'layouts/blog/breadcrumb', data: { :current => 'Article', :breadcrumb => [{ :name => 'Home', :url => root_path }] } %>

  <div class="card ">
    <div class="card-body">
      <div class="d-flex justify-content-between">
        <h5 class="card-title"><%= @article.title %></h5>
        <%= render "followers/follow_btn", user: @user %>
      </div>
      <h6 class="card-subtitle mb-2 text-muted"><%= @article.user.full_name %></h6>
      <p class="card-text"><%= @article.body %></p>
      <small>Published on: <%= @article.created_at %></small>

      <div class="d-flex justify-content-end align-items-center mt-2 gap-3">
        <% if user_signed_in? && @article.user_id == current_user.id %>
          <%= link_to "Edit", edit_article_path(@article) %>
          <%= form_with url: @article, method: :delete, id: 'delete_article_form' do |form| %>
            <%= form.button 'Delete', class: 'btn btn-link' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="m-2 p-2">
    <h5>Comments</h5>

    <% if @article.comments.present? %>
      <%= render @article.comments %>
    <% else %>
      <small>No comments ...</small>
    <% end %>

  </div>

  <h4>Add a comment:</h4>
  <% if user_signed_in? %>
    <% if @user.followed_by?(current_user.id) || @user.id == current_user.id %>
      <%= render 'comments/form' %>
    <% else %>
      <span>follow the user for comment</span>
    <% end %>
  <% else %>
    <span><%= link_to 'Login', new_user_session_path %> for comment</span>
  <% end %>
<% end %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <div class="card border-success mb-3" style="border-width: 0 0 0 3px">
    <div class="card-body">
      <h6 class="card-subtitle mb-2 text-muted"><%= comment.commenter %></h6>
      <p class="card-text"><%= comment.body %></p>

      <div class="d-flex justify-content-between mt-2 gap-3">
        <small>Published on: <%= comment.created_at %></small>

        <% if user_signed_in? && comment.user_id == current_user.id %>
          <%= form_with url: [comment.article, comment], method: :delete, id: 'delete_comment_form' do |form| %>
            <%= form.button 'Delete', class: 'btn btn-link' %>
          <% end %>

        <% end %>

      </div>

    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [@article, @article.comments.build] do |form| %>
  <div class="card">
    <div class="card-body">
      <%= form.hidden_field :user_id, value: current_user.id %>
      <div class="mb-3">
        <%= form.label :commenter, class: 'form-label' %>
        <%= form.text_field :commenter, class: 'form-control', placeholder: 'Commenter', required: 'require', readonly: 'readonly', value: current_user.full_name %>
      </div>
      <div class="mb-3">
        <%= form.label :body, class: 'form-label' %>
        <%= form.text_area :body, class: 'form-control', rows: 3, required: 'require' %>
      </div>

      <div class="mb-3">
        <%= form.label :status, class: 'form-label' %>
        <%= form.select :status, valid_statuses, {}, { class: 'form-control' } %>
      </div>

      <div>
        <%= form.submit class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/followers/_follow_btn.erb
<% if user_signed_in? && current_user.id != user.id %>
  <% following = user.followed_by(current_user.id) %>
  <% if following.present? %>
    <%= form_with model: following, method: :delete do |form| %>
      <%= form.button '', class: 'btn badge bg-danger rounded-pill', title: 'Unfollow' do %>
        Unfollow <i data-feather="user-minus"></i>
      <% end %>
    <% end %>
  <% else %>
    <%= form_with model: Follower, method: :post do |form| %>
      <%= form.hidden_field :followed_user_id, value: user.id %>
      <%= form.hidden_field :followed_by_user_id, value: current_user.id %>
      <%= form.button '', class: 'btn badge bg-primary rounded-pill', title: 'Follow' do %>
        Follow <i data-feather="user-plus"></i>
      <% end %>
    <% end %>
  <% end %>

<% end %>

app/views/followers/index.html.erb
<% content_for :blog_body do %>
  <%= render 'layouts/blog/breadcrumb', data: { :current => 'Users', :breadcrumb => [{ :name => 'Home', :url => root_path }] } %>

  <h1 align="center">Users</h1>

  <ul class="list-group">
    <% @users.each do |user| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= user.full_name %>
        <%= render 'followers/follow_btn', user: user %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstBlog</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  <%= javascript_include_tag :application, integrity: true %>
  <!--  feather icons cdn-->
  <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
</head>

<body>
<% if content_for? :blog_body %>
  <header>
    <%= render 'layouts/blog/navbar' %>
  </header>
  <main role="main" class="p-3">
    <%= yield :blog_body %>
  </main>
<% else %>
  <%= yield %>
  <!--flash message required to devise gem-->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<% end %>

<script>
    // use feather icons
    feather.replace()
</script>

</body>
</html>

app/views/layouts/blog/_breadcrumb.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb justify-content-end">
    <% data[:breadcrumb].each do |item| %>
      <li class="breadcrumb-item"><%= link_to item[:name], item[:url] %></li>
    <% end %>
    <li class="breadcrumb-item active" aria-current="page"><%= data[:current] %></li>
  </ol>
</nav>

app/views/layouts/blog/_navbar.erb
<!--  start navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'Articles Blog', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Bloggers', followers_path, class: 'nav-link active' %>
        </li>
      </ul>
      <div class="d-flex gap-3">
        <% if user_signed_in? %>
          <%= link_to 'New post', new_article_path, class: 'btn btn-success' %>
        <% end %>
        <div class="btn-group">
          <button class="btn btn-transparent rounded-circle text-white" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <i data-feather="<%= user_signed_in? ? 'user-check' : 'user' %>"></i>
          </button>
          <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="dropdownMenuButton1">
            <li><h6 class="dropdown-header"><%= user_signed_in? ? 'Logged user' : 'Guest user' %></h6>
              <% if user_signed_in? %>
                <small class="mx-3"><%= current_user.email %></small>
                <hr class="dropdown-divider">
              <% end %>
            </li>
            <% if user_signed_in? %>
              <li><%= link_to 'Profile',edit_user_registration_path, class: 'dropdown-item'   %></li>
            <% end %>
            <li>
              <hr class="dropdown-divider">
            </li>
            <% if user_signed_in? %>
              <li>
                <%= link_to destroy_user_session_path, class: "dropdown-item text-danger d-flex justify-content-center align-items-center gap-1" do %>
                  <i data-feather="log-out" style="width: 1rem"></i> logout
                <% end %>
            <% else %>
              <li>
                <%= link_to new_user_session_path, class: "dropdown-item text-success d-flex justify-content-center align-items-center gap-1" do %>
                  login  <i data-feather="log-in" style="width: 1rem"></i>
                <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>
<!--end navbar-->